### ISSUE TITLE
Error with "runs" request - Database job_data_t0n3.experiment_run corrupted

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#16]
In GitLab by @eferre1 on Dec 5, 2022, 14:40

Hi, since the last week, I'm having an error with the next request that we used in the testing suite to create a performance comparison between two runs. It is only happening for the `t0n3` experiment, so I think it is more of a random corruption of the database or similar, more than anything related to the latest changes to the API.

This is the request we use:

```
http://192.168.11.91:8081/runs/t0n3
```

I tried to access the request via browser (firefox) and this was the output:

```json
 error:          true                                           
 error_message:  "invalid literal for int() with base 10: 'NA'" 
 runs:           []                                             
```

And here it is the error that the python code complains (it is out of range because it is an empty list due to the results shown above) due to this:

```
Traceback (most recent call last):
  File "./testing_suite.py", line 829, in <module>
    main()
  File "./testing_suite.py", line 726, in main
    historic_performance(my_experiments)
  File "./testing_suite.py", line 399, in historic_performance
    last_run = [run for run in historic_performance_metrics if run["run_id"] == max(run["run_id"] for run in historic_performance_metrics)][0]
IndexError: list index out of range
```

in API side:

```
     14 Traceback (most recent call last):
     15   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
     16     response = self.full_dispatch_request()
     17   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
     18     rv = self.handle_user_exception(e)
     19   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
     20     return cors_after_request(app.make_response(f(*args, **kwargs)))
     21   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
     22     rv = self.dispatch_request()
     23   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
     24     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
     25   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/app.py", line 241, in get_runs
     26     result = CommonRequests.get_experiment_runs(expid)
     27   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/experiment/common_requests.py", line 1492, in get_experiment_runs
     28     raise exp
     29   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/experiment/common_requests.py", line 1438, in get_experiment_runs
     30     experiment_runs = experiment_history.manager.get_experiment_runs_dcs() # job_data_structure.get_experiment_runs()
     31   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/history/database_managers/experiment_history_db_manager.py", line 219, in get_experiment_runs_dcs
     32     return [ExperimentRun.from_model(row) for row in experiment_run_rows]
     33   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/history/database_managers/experiment_history_db_manager.py", line 219, in <listcomp>
     34     return [ExperimentRun.from_model(row) for row in experiment_run_rows]
     35   File "/root/miniconda3/envs/autosubmit_api/lib/python3.7/site-packages/autosubmit_api/history/data_classes/experiment_run.py", line 115, in from_model
     36     experiment_run.finish = int(row_dict.get('finish', 0))
```

Can you take a look @ jberlin? Thanks.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 5, 2022, 15:29

At first sight this shouldn't happen, the `experiment_runs` table from the experiment metadata is not empty. So there are runs to be shown.

I'll look further into this.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Dec 5, 2022, 15:32

Hi @eferre1 , I will have a look, to execute the API call, why do you use an IP address? you can use the alias directly for the call and avoid issues like if an IP address change takes place:

```https://earth.bsc.es/autosubmitapi/runs/t0n3```

concerning the issue ...is it strange, I don't see anything in the log of the API, I guess the exception is being handled in the code, and that is the reason there is nothing in the AS API logs:

```
[2022-12-05 14:46:42 +0000] [10964] [INFO] ERUNS|RECEIVED|t0n3
[2022-12-05 14:46:42 +0000] [10964] [INFO] ERUNS|RTIME|0.086658000946
```

@ggcr, we will need to add the following changes:

- Check if we are trying to cast string literals to int/float values from DB 
- In all calls in common.request, add `app.logger.info()` in the exception handlers, so we can quickly detect issues in the future by simply opening the log of the running instance of gunicorn, currently, most of the calls that intercept exceptions don't have the logger in common. requests, only at app level :

```
def get_experiment_runs(expid):
--
--
except Exception as exp:
    print(traceback.format_exc())
    error = True
    error_message = str(exp)
    pass
```

We can discuss this if these changes can have big impact

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Dec 5, 2022, 15:54

We are using the IP since I implemented the code (https://earth.bsc.es/gitlab/es/testing_suite/-/issues/28), and I just copied what was already implemented for other requests in the testing suite code and modified it. I will open an issue there to update it in all the requests to have a more robust code, thanks for the advice.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 5, 2022, 16:06

Thanks for the detailed answer. It is really helpful @ jberlin 

So far I've traced down the bug up until the `ExperimentRun.from_model` from our `experiment_history_db_manager` with the following exception:

```
EXCEPTION: invalid literal for int() with base 10: 'NA'
EXCEPTION: invalid literal for int() with base 10: 'month'
EXCEPTION: invalid literal for int() with base 10: '{"platforms": {"nord3v2": {"QUEUE": "bsc_es"...'
```

Seems like there is a problem with the casting of the experiment_runs rows.

More precisely we are trying to cast the field `('finish', 'month')` as an int, thus receiving the above exception.

I have checked other experiments and as the finish field they have values such as: 

```
'finish': 0
'finish': 1634959169
...
```

So yeah, `finish` should be an `int`. And we are receiving a `string`. **Seems like there is some row corrupted that is affecting all the others** but I am not sure yet. Whenever I can I will do some tests comparing a working experiment and this one to determine if it's an isolated db problem or we have something wrong.

FYI: @eferre1

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Dec 5, 2022, 16:11

good finding @ggcr , it looks like a different type of info was saved experiment_runs table for that particular experiment I guess

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 7, 2022, 11:42

Hi @eferre1 

My initial guess is because this history module of Autosubmit responsible of creating new runs changed recently has been updated adding new fields (see [Issue #847: Database runid update](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/847)) the first runs of the experiments were not stored correctly and are shifted in the .db file, that is, the "FINISHED" field is receiving the value of the next column, but this **affected rows are only the first runs**.

I managed to be able to display it and the last runs are correct as you can see in our local dev env https://bscesautosubmitdev01.bsc.es/autosubmitapi/runs/t0n3 .

In your case you only want this last run, right? Or are you consuming also data from older runs?

In any case I will try to get involved in the History module of Autosubmit to see a method of correctly store all runs. Because it is a module made for the GUI/API consumption and we should take care of that.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Dec 7, 2022, 11:54

> In your case you only want this last run, right? Or are you consuming also data from older runs?

With the current code of the testing suite, we are only using the last run, successful or not, and the previous successful run. But to find that previous successful run we take the info from the `runs` request and check for the ones with all jobs successfully finished.

We had in mind a possible new feature to create a performance graph, comparing all the runs (since checking only against the last one might not show a big but gradual decrease/increase in performance), but this was only an idea and it is not even in the process of being implemented yet. This is related with the issue #847 since we wanted to have all the experiments graphs change the run id at the same point (from week to week, and not in a rerun to fix bugs) so we could compare also any significant change in performance across experiment, so I guess that we would ask for a reset of the db in that case.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 22, 2022, 08:48

mentioned in issue autosubmitreact#62

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Dec 22, 2022, 08:50

marked this issue as related to autosubmitreact#62

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jan 26, 2023, 10:20

@eferre1 can you remove the databases for this experiment and create it again? @ jberlin or @ggcr can help you to find the directories and files

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jan 26, 2023, 11:23

Hi @eferre1 , for this experiment, the DBs are the following:

```
ll  /esarchive/autosubmit/t0n3/pkl/
total 130
-rw-r--r-- 1 eferre1 Earth 3004 Oct 27 13:03 27102022130356_job_list_t0n3.pkl
-rw-r--r-- 1 eferre1 Earth 2886 Dec 21 05:12 job_list_t0n3_backup.pkl
-rw-r--r-- 1 eferre1 Earth 2886 Dec 21 05:12 job_list_t0n3.pkl
-rw-r--r-- 1 eferre1 Earth 4096 Dec 20 08:30 job_packages_t0n3.db
```
Can you please make a backup of these and delete them and re-create the experiment ? just to check if the issue persist

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Jan 31, 2023, 15:58

I moved the `pkl` folder to a backup path, and created it again and recreated the experiment:

```bash
eferre1@bscesautosubmit02:~> cd /esarchive/autosubmit/t0n3/
eferre1@bscesautosubmit02:/esarchive/autosubmit/t0n3> mv pkl/ pkl_bckp/
eferre1@bscesautosubmit02:/esarchive/autosubmit/t0n3> mkdir pkl
eferre1@bscesautosubmit02:/esarchive/autosubmit/t0n3> autosubmit create -np t0n3
```

But I'm still getting the index out of range error in the compare_performance from the testing suite that uses the `runs` request from the API:

```
autosubmit version:
3.14.0b

Traceback (most recent call last):
  File "./testing_suite.py", line 831, in <module>
    main()
  File "./testing_suite.py", line 728, in main
    historic_performance(my_experiments)
  File "./testing_suite.py", line 401, in historic_performance
    last_run = [run for run in historic_performance_metrics if run["run_id"] == max(run["run_id"] for run in historic_performance_metrics)][0]
IndexError: list index out of range
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jan 31, 2023, 17:29

@ jberlin can you debug this one as soon as you have some time?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jan 31, 2023, 17:30

ok

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 21, 2023, 19:42

@ jberlin please remind to verify if all these (and GUI) issues are still an issue and tag them appropriately, as also as put them into corresponding milestones.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Mar 22, 2023, 16:53

Thank @ jberlin. While @eferre1 answers, there are some issues in testing or assigned to Cristian. Could you verify if those could be closed or otherwise assign them to someone else?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 5, 2023, 17:51

in development environment I also get the same error:

http://192.168.11.42:8081/runs/t0n3

{"error":true,"error_message":"invalid literal for int() with base 10: 'NA'","runs":[]}

I will try to remove the exception handler or at least to check where is the issue exactly, because this info is totally useless

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 5, 2023, 18:08

Did you check if it's what @ggcr was suggesting? A field receiving data in an unexpected type, maybe because a different kind of data is introduced. Maybe checking in the experiment ddbb you find that there is one of the registries that looks different than the others.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 6, 2023, 13:31

There are inconsistencies with the DB for the mentioned experiment as Cristian pointed out, the values seems to be shifted one column as we can see :

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/39b7b3b9d9c15280d8da16f3df3a3f0d/image.png)

Then parsing of these values fails, also is weird that when creating these rows, if columns have a defined type in the database (int, string, etc) it should be not possible to make these insertions, for instance SUSPENDED column is of type int, however it was possible to insert a string with the metadata......

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/1ab3d597aa210f5c67eaa676cd90002f/image.png)

@eferre1 , which is expid of the copy of the t0n3 experiment ? so we can check also the structure.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Apr 6, 2023, 14:21

From my side, these experiments should be similar (maybe not a direct copy but same base configuration from different releases):

`t045`, `t06b`, `t0ap`

Then, `t0bf` `t0bx` are not mine (those belong to Genis), but are also the same case experiment and I think that those were direct copies from `t0n3` (maybe with later modifications in the config but again, same base case).

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 6, 2023, 14:55

thanks for the info,

for t0bf

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/b778be4be85166ab80b0f8616e276833/image.png)

for t0bx

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/1f1f983d0418207e8ac5e3115190805f/image.png)

the structure of these is correct, the `job_data_t0n3.db` database file seems corrupt but running the check SQLite have for this doesn't indicate this:

 ```
sqlite3 job_data_t0n3.db "PRAGMA integrity_check"
 ok
```

I also see that there were some issues before, did you try to recreate again the database @eferre1 ?:

```
(base) bscearth357 /esarchive/autosubmit/as_metadata/data  > ll *t0n3*
-rwxrwxrw- 1 eferre1 Earth 1091584 Oct 27 13:01 job_data_t0n3_corrupted.db
-rwxrwxrw- 1 eferre1 Earth 1244160 Mar  3 18:19 job_data_t0n3.db
-rw-r--r-- 1 eferre1 Earth 1158263 Mar  3 18:19 job_data_t0n3.sql
```

The first line of job_data_t0n3.sql has

INSERT INTO "experiment_run" VALUES(1,'2021-06-04-15:25:21','0',0,'NA','0',0,0,0,0,0,0,0,'',NULL);

It should have thrown an error since `finish` column is of type integer, the only way to recover the experiment is to properly edit the SQL script and set the values in the right columns...again this is extremely weird since you should not be able to insert strings in an integer field/column type in a good decent database (in the normal world).

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 6, 2023, 15:06

now I see why:

```
(3) SQLite lets me insert a string into a database column of type integer!

This is a feature, not a bug. SQLite uses dynamic typing. It does not enforce data type constraints. Data of any type can (usually) be inserted into any column. You can put arbitrary length strings into integer columns, floating point numbers in boolean columns, or dates in character columns. The datatype you assign to a column in the CREATE TABLE command does not restrict what data can be put into that column. Every column is able to hold an arbitrary length string. (There is one exception: Columns of type INTEGER PRIMARY KEY may only hold a 64-bit signed integer. An error will result if you try to put anything other than an integer into an INTEGER PRIMARY KEY column.)

But SQLite does use the declared type of a column as a hint that you prefer values in that format. So, for example, if a column is of type INTEGER and you try to insert a string into that column, SQLite will attempt to convert the string into an integer. If it can, it inserts the integer instead. If not, it inserts the string. This feature is called type affinity.
```
So SQLite doesn't do any checks of any type on creating rows even if the column has a given type; this is a serious issue since, at any time, a db can become corrupt easily from a logic perspective. We may try to enforce type checking before making any insert; here are some hints on how to achieve it:

https://stackoverflow.com/questions/49230311/is-it-possible-to-enforce-sqlite-datatypes

Unfortunately, this approach can be applied when creating new DBs....,  @dbeltrankyl maybe this can be applied somehow? not having any type check on inserting values in autosubmit DBs is totally error-prone. 

@eferre1 if you want to recover t0n3 we can try to edit the SQL file and manually put the right values in each insert, otherwise for the moment, I don't foresee any suitable solution

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Apr 6, 2023, 15:25

>  did you try to recreate again the database @eferre1 ?:

I think we did at some point, but I'm not sure about it.

> @eferre1 if you want to recover t0n3 we can try to edit the SQL file and manually put the right values in each insert, otherwise for the moment, I don't foresee any suitable solution

Ok, for the moment it doesn't affect me a lot, but if I need it in the future I'll let you know, thanks.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Apr 11, 2023, 09:52

> Unfortunately, this approach can be applied when creating new DBs...., @dbeltrankyl maybe this can be applied somehow? not having any type check on inserting values in autosubmit DBs is totally error-prone.

* Actually, autosubmit dbfix recreates the database, so we could do it for all experiments on autosubmit run  if Autosubmit looks at the db file creation date ( and uses 3.15.0 ) 

> @eferre1 if you want to recover t0n3 we can try to edit the SQL file and manually put the right values in each insert, otherwise for the moment, I don't foresee any suitable solution

There should be an .SQL that has the db data so it should be a matter of edit that file and recreate the db

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Apr 11, 2023, 09:53

@ jberlin , maybe you can open an issue on autosubmit git?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 13, 2023, 09:47

Good debugging work @ jberlin 

Yes @dbeltrankyl, @ jberlin missed the part of opening an issue in Autosubmit project

> Summarizing what we discussed in the Autosubmit meeting, many of the last issues in the API and GUI could be connected with inconsistencies in the DDBB. @ jberlin will check the DB's for the affected experiments, look for those inconsistencies and report in the Autosubmit project to nail down the issues in the origin.

I think that, as @ jberlin says, the Autosubmit functions inserting any data in the DBs should have a check for the data types.

> Actually, autosubmit dbfix recreates the database, so we could do it for all experiments on autosubmit run if Autosubmit looks at the db file creation date ( and uses 3.15.0 )

I think that Autosubmit should check, on `autosubmit run` if the DB has the right types and otherwise recreate it properly. This would also work in case that there are future issues.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Apr 13, 2023, 10:10

There's also this one that maybe would work? https://stackoverflow.com/a/49241453

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/fc8d49d49b34c64b827b8da857ef144d/image.png)

Although I am not sure if that won't result in performance issues.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 14, 2023, 09:17

Hi @kinow , yes that what I saw, I think it may work ! I will creae an issue in Autosubmit and discuss this overthere

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 14, 2023, 10:17

I'm updating on the discussion yesterday in our weekly meeting:

Looking at the [plot](https://earth.bsc.es/gitlab/es/autosubmit_api/-/issues/16#note_209875) by @ jberlin it seems like the more recent records are actually ok, while the older where lacking a column. So, besides adding checks in the DDBB and Autosubmit, @ jberlin should probably have to do something in the API, if it was working well with the incomplete records and not with the good ones...

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 14, 2023, 13:25

mentioned in issue autosubmit#1014

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 14, 2023, 13:26

I created issue [#1014](https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1014) in AS project

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 18, 2023, 15:34

I edited by hand the SQL file I am attaching, so @eferre1 please follow these next steps:

1. Make a backup of job_data_t0n3.sql
2. Replace the job_data_t0n3.sql by the one I am attaching below (rename the file accordingly first)
3. Run `autosubmit dbfix t0n3`
4. The data now should have the fields in the right position

[t0n3_experiment_runs.sql](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/2469f90ed6dba5133681b29699e7fa79/t0n3_experiment_runs.sql)

I hope it works

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Apr 20, 2023, 15:53

I'm not sure if I did it correctly, but it didn't work, I did this (where the file in my scratch is the one you provided):

```
eferre1@bscesautosubmit01:~> mv /esarchive/autosubmit/as_metadata/data/job_data_t0n3.sql /esarchive/autosubmit/as_metadata/data/job_data_t0n3.sql_bckp
mv /esarchive/scratch/bsc32627/tmp/t0n3_sql /esarchive/autosubmit/as_metadata/data/job_data_t0n3.sql
eferre1@bscesautosubmit01:~> autosubmit dbfix t0n3
Autosubmit is running with 3.14.0
mv: replace ‘/esarchive/autosubmit/as_metadata/data/job_data_t0n3_corrupted.db’, overriding mode 0644 (rw-r--r--)? y
## Here it was waiting for my input, so I typed `y` and pressed enter.
Original database moved.
Restoring from sql


eferre1@bscearth358:~/testing_suite/source> ./ts.sh --config_file config.yml.tsxp --compare_performance
autosubmit version:
3.14.0

Traceback (most recent call last):
  File "./testing_suite.py", line 831, in <module>
    main()
  File "./testing_suite.py", line 728, in main
    historic_performance(my_experiments)
  File "./testing_suite.py", line 401, in historic_performance
    last_run = [run for run in historic_performance_metrics if run["run_id"] == max(run["run_id"] for run in historic_performance_metrics)][0]
IndexError: list index out of range
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 27, 2023, 17:06

I added the checks for the columns; the checks does it work:

```
CREATE TABLE experiment_run (
      run_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
      created TEXT NOT NULL CHECK (typeof(created) = 'text'),
      modified TEXT NOT NULL CHECK (typeof(modified) = 'text'),
      start INTEGER NOT NULL CHECK (typeof(start) = 'integer'),
      finish INTEGER CHECK (typeof(finish) IN ('integer', 'null')),
      chunk_unit TEXT NOT NULL CHECK (typeof(chunk_unit) = 'text'),
      chunk_size INTEGER NOT NULL CHECK (typeof(chunk_size) = 'integer'),
      completed INTEGER NOT NULL CHECK (typeof(completed) = 'integer'),
      total INTEGER NOT NULL CHECK (typeof(total) = 'integer'),
      failed INTEGER NOT NULL CHECK (typeof(failed) = 'integer'),
      queuing INTEGER NOT NULL CHECK (typeof(queuing) = 'integer'),
      running INTEGER NOT NULL CHECK (typeof(running) = 'integer'),
      submitted INTEGER NOT NULL CHECK (typeof(submitted) = 'integer'),
      suspended INTEGER NOT NULL DEFAULT 0 CHECK (typeof(suspended) = 'integer'),
      metadata TEXT CHECK (typeof(metadata) IN ('text', 'null')) 
      );
```

but it doesn't give much accurate information

```
(base) bscearth357 /esarchive/autosubmit/as_metadata/data  > autosubmit dbfix t0n3
Autosubmit is running with 3.14.0
Original database moved.
Restoring from sql
Error: near line 23: CHECK constraint failed: experiment_run
Error: near line 25: CHECK constraint failed: experiment_run
Error: near line 27: CHECK constraint failed: experiment_run
Error: near line 29: CHECK constraint failed: experiment_run
Error: near line 31: CHECK constraint failed: experiment_run
Error: near line 33: CHECK constraint failed: experiment_run
Error: near line 35: CHECK constraint failed: experiment_run
Error: near line 37: CHECK constraint failed: experiment_run
Error: near line 39: CHECK constraint failed: experiment_run
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Apr 27, 2023, 17:19

I made few minor modifications to the scripts and I ran the dbfix, now seems fine @eferre1 :

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/360bc5451456fa09db5b2020e0d234ed/image.png)

Please let me know if you still face the same issue, the fix was carried out for table `experiments_run`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 28, 2023, 19:08

Even if it's not accurate, if it returns error when the specifications are not matched, that's something. Besides doing it's own checks, Autosubmit would know if the registry was inserted.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 28, 2023, 19:09

So, should we able to check the previous runs?

I see this message when I click on the clock.

`There are not runs recorded for this experiment. Are you running the latest version of Autosubmit that implements the historic database?`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on May 11, 2023, 10:22

@eferre1 could you check that the changes in the DDBB are working?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on May 11, 2023, 15:16

I'm still having the error:

```
eferre1@bscearth358:~/testing_suite/source> ./ts.sh --config_file config.yml.tsxp --compare_performance
autosubmit version:
3.14.0

Traceback (most recent call last):
  File "./testing_suite.py", line 831, in <module>
    main()
  File "./testing_suite.py", line 728, in main
    historic_performance(my_experiments)
  File "./testing_suite.py", line 401, in historic_performance
    last_run = [run for run in historic_performance_metrics if run["run_id"] == max(run["run_id"] for run in historic_performance_metrics)][0]
IndexError: list index out of range
```

and if I comment the `t0n3` from the config it works:
<details><summary>results without t0n3 experiment</summary>

```
eferre1@bscearth358:~/testing_suite/source> ./ts.sh --config_file config.yml.tsxp --compare_performance
autosubmit version:
3.14.0

| expid | SYPD (previous) | ASYPD (previous) | details | hpc     |
|-------|------------|------------|---------|---------|
| t0n2  | 59.98 (-3.09) | 21.02 (+16.14) | weekly test case: ORCA1L75 + nudging + surface restoring | marenostrum4 | 
| t0n4  | 14.2 (-0.56) | 2.61 (-0.87) | weekly test case: T255L91-ORCA1L75 (t0nf ICs). ScenarioMIP/ssp245 outclass | marenostrum4 | 
| t0n5  | 1.77 (-0.15) | 1.06 (-0.2) | weekly test case: T255L91-TM5 full chem | marenostrum4 | 
| t0n6  | 1.98 (-0.05) | 0.56 (-0.65) | weekly test case: T255L91-ORCA1L75-TM5 full chem | marenostrum4 | 
| t0n7  | 11.41 (-1.45) | 0.51 (-5.18) | weekly test case: T255L91-ORCA1L75-LPJG-PISCES | marenostrum4 | 
| t0n8  | 7.05 (-0.47) | 4.84 (+1.59) | weekly test case: T255L91-ORCA1L75-LPJG-PISCES-TM5 co2,co2fb | marenostrum4 | 
| t0n9  | 99.08 (-5.52) | 5.74 (-44.54) | weekly test case: OSM-LPJG (res account) | marenostrum4 | 
| t0na  | 27.1 (-0.08) | 10.79 (+4.88) | weekly test case: ORCA1L75-PISCES | marenostrum4 | 
| t0nb  | 36.73 (-0.97) | 1.2 (+0.66) | weekly test case: ORCA1L75 CMORIZATION FALSE | marenostrum4 | 
| t0nd  | 23.34 (+0.84) | 7.22 (+6.9) | weekly test case: ORCA1L75 | nord3v2 | 
| t0ne  | 41.26 (+2.76) | 1.46 (+0.92) | weekly test case: ORCA1L75 - 000/INTERMEDIATE_STORAGE | marenostrum4 | 
| t0nf  | 16.28 (-2.21) | 1.21 (+0.74) | weekly test case: T255L91-ORCA1L75 cold start - 000/INTERMEDIATE_STORAGE | marenostrum4 | 
| t0ng  | 3.15 (-0.17) | 1.38 (+1.08) | weekly test case: ORCA025L75 (NEMO only) | marenostrum4 | 
| t0nh  | 3.33 (-1.33) | 1.44 (+1.13) | weekly test case: T511L91 | marenostrum4 | 
| t0ni  | 2.64 (-0.54) | 1.76 (-1.36) | weekly test case: T511L91-ORCA025L75 | marenostrum4 | 
| t0nj  | 15.85 (-1.1) | None (No stats) | weekly test case: T255L91-ORCA1L75 (simplified workflow) | marenostrum4 | 
```

</details>

Should I try running the experiment just in case that it updates the ddbb?
