### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#25]
In GitLab by @kinow on Jul 31, 2023, 10:15

In the testing suite tests @rohanali1798 and I did some days ago, we found several errors. Some related to Python 3, others were legit bugs in the code.

The code is swallowing a lot of useful tracebacks. This issue is a placeholder for someone to go over the code, add good logging, and confirm the exceptions are being correctly logged.

By default they don't need to appear, but it's important that when troubleshooting issues we are able to enable them.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Jul 31, 2023, 10:16

mentioned in issue digital-twins/de_340/project_management#477

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Jul 31, 2023, 10:18

Here's what I did in a branch to test

```diff
diff --git a/autosubmit_api/workers/populate_details/populate.py b/autosubmit_api/workers/populate_details/populate.py
index b59ce34..71bafb4 100644
--- a/autosubmit_api/workers/populate_details/populate.py
+++ b/autosubmit_api/workers/populate_details/populate.py
@@ -34,6 +34,7 @@ class DetailsProcessor:
 
   def _get_experiments(self):
     # type: () -> List[Experiment]
+    return [Experiment(158, 'a03t')]
     experiments = []
     conn = self._get_new_connection()
     cur = conn.cursor()
@@ -70,12 +71,13 @@ class DetailsProcessor:
           exp_ids.add(experiment.id)
       except IOError:
         # Ignore file not found errors
-        pass
+        print(traceback.format_exc())
       except ParsingError:
         # Ignore parsing errors
-        pass
+        print(traceback.format_exc())
       except Exception as exp:
         print(("Error on experiment {}: {}".format(experiment.name, str(exp))))
+        print(traceback.format_exc())
     return result
 
   def _insert_many_into_details_table(self, values):
```

Where the code was printing nothing, after this change it

```bash
(venv) [brunokino@climatedt-wf autosubmit_api]$ python -m autosubmit_api.workers.populate_details_db
Error on experiment a03t: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/brunokino/autosubmit_api/autosubmit_api/workers/populate_details/populate.py", line 61, in _get_all_details
    detail = self._get_details_data_from_experiment(experiment.name)
  File "/home/brunokino/autosubmit_api/autosubmit_api/workers/populate_details/populate.py", line 51, in _get_details_data_from_experiment
    autosubmit_config = ConfigurationFacadeDirector(AutosubmitConfigurationFacadeBuilder(expid)).build_autosubmit_configuration_facade(self.basic_config)
  File "/home/brunokino/autosubmit_api/autosubmit_api/builders/configuration_facade_builder.py", line 74, in build_autosubmit_configuration_facade
    self.builder.generate_autosubmit_config()
  File "/home/brunokino/autosubmit_api/autosubmit_api/builders/configuration_facade_builder.py", line 45, in generate_autosubmit_config
    self.autosubmit_config = AutosubmitConfig(self.expid, self.basic_config, ConfigParserFactory())
  File "/home/brunokino/autosubmit_api/autosubmit_api/config/config_common.py", line 70, in __init__
    self._configWrapper = ymlConfigStrategy(expid, basic_config, parser_factory, ".yml")
  File "/home/brunokino/autosubmit_api/autosubmit_api/config/ymlConfigStrategy.py", line 53, in __init__
    self._conf_parser.reload(True)
  File "/home/brunokino/autosubmit_api/venv/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 1386, in reload
    starter_conf = self.substitute_dynamic_variables(starter_conf)
  File "/home/brunokino/autosubmit_api/venv/lib64/python3.9/site-packages/autosubmitconfigparser/config/configcommon.py", line 812, in substitute_dynamic_variables
    if len(aux_dict) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Jul 31, 2023, 10:24

mentioned in issue ces/autosubmit4-config-parser#4
