### ISSUE TITLE
The API needs to be updated to be able to read AS4 configurations for experiments created with the -min flag

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#27]
In GitLab by @mcastril on Aug 4, 2023, 15:27

By using the -min flag, Autosubmit will generate a minimal configuration in a `minimal.yml` file, that can be complemented with other files added by the user (including configurations that can live in a repository).

The API is only prepared to read files following the classical partition (autosubmit, expdef, jobs, platforms, projects) YML files.

CC @kinow @rohanali1798 @dbeltrankyl

**Comment by LuiggiTenorioK** [comment]
In GitLab by @rohanali1798 on Sep 19, 2023, 12:23

Yes, I can also confirm this as I'm testing the API locally on my system:

```
rahmed@bsces109872:~$ http://0.0.0.0:8081/expinfo/a006

{"branch":"","chunk_size":0,"chunk_unit":"default","completed_jobs":0,"db_historic_version":"NA","description":"","error":true,"error_message":"Required file not found /home/rahmed/Desktop/playing_with_api/a006/conf/autosubmit_a006.conf","expid":"a006","hpc":"","model":"","owner":"NA","owner_id":0,"path":"NA","pkl_timestamp":1695118852,"running":false,"time_last_access":"","time_last_mod":"","total_jobs":0,"updateTime":0,"version":""}
```

Required file not found `/home/rahmed/Desktop/a006/conf/autosubmit_a006.conf`

Since it is looking for classical YML files. 

CC: Luiggi

**Comment by LuiggiTenorioK** [comment]
Just tested this endpoint. The `.conf` issue seems to be solved by the commit of @kinow. Then, another issue pop-up in this same endpoint:

```
Traceback (most recent call last):
  File "/home/ltenorio/projects/autosubmit_api/autosubmit_api/experiment/common_requests.py", line 160, in get_experiment_data
    result["description"] = db_common.get_experiment_by_id(expid)["description"]
  File "/home/ltenorio/projects/autosubmit_api/autosubmit_api/database/db_common.py", line 500, in get_experiment_by_id
    result['description'] = str(row[4])
IndexError: tuple index out of range
```

Seems like the columns from the `experiment` table changed between versions and this will affect every place where this data is retrieved using the column order. Already addressed this issue on this endpoint in commit 0ca905ca.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Oct 16, 2023, 16:18

>Seems like the columns from the `experiment` table changed between versions

Ah, BTW, I now recall we had some issues, just before Julian left, with changes in tables and columns. I think somewhere in the code we had a situation where we used to have 3 columns, and now had 4, and then a value was `NULL` or `None`.

The main problem, however, was that everything worked! But part of the UI showed as if data was missing, even though the data was clearly in the table. Just in case you find something similar...  :thumbsup:

**Comment by LuiggiTenorioK** [comment]
Also found the same `.conf` error message on the `populate_queue_run_times` worker because it was using legacy code. Fixed it on commit 74066f54c9124087c02dc98cb6d43b2647c9774c.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Oct 18, 2023, 20:18

Great to read this, @LuiggiTenorioK 

The issues that Bruno are talking about are critical because we discovered that we lack checks at the time of introducing data in the DDBB. Sooner than later I planned to let you know about it, because it's something that you should address in the short-medium term.

The related issues are:

https://earth.bsc.es/gitlab/es/autosubmit_api/-/issues/16
https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1014
https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1007

Our plan was to add:

* Type definitions in the databases (Julián proposal, that didn't go to production)
* Checks in Autosubmit at the time of introducing the data
* Checks in the API or in the GUI at the time of reading

We have to avoid that the insertion of an additional column that is not in the specification breaks all the service downstream

**Comment by LuiggiTenorioK** [comment]
Great idea! I realized that the API project lacks a model layer to map every abstraction to the persistence layer of the application. This is bad as a data object is called from multiple parts of the code and in different ways, violating the first principle of **S**OLID. So, it happens that you have to track all the functions that interact with a specific table in order to fix an issue.

I usually use [Pydantic](https://docs.pydantic.dev/latest/) to have a easy to read model layer with automatic validation, and it should work fine for our Python projects too. This library is used by default in FastAPI to validate requests and responses too. @kinow @dbeltrankyl maybe you can take a look at this library too for autosubmit.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @kinow on Oct 19, 2023, 23:27

I used Pydantic in previous projects too, and I **think** we have at least one other project at the BSC, in ES, I think the web application that @pabretonniere presented some months ago was written in Python with FastAPI and Pydantic, handling user input validation.

Maybe it could be something that we could add in Autosubmit, but we will have to check the impact of doing that, and whether the code is ready for that or if it needs some refactoring and cleaning first (maybe old code could force us to write validation rules that look a bit yuck)

**Comment by LuiggiTenorioK** [comment]
mentioned in commit d68b9d0816307b8de8f0e980bdae02dab550759b

**Comment by LuiggiTenorioK** [comment]
The issue has already been tested since v4.0.0b2 and working in the Climate DT VM :tada:
