### ISSUE TITLE
I/O error cause db tables to be corrupted

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#62]
In the CLimate DT VM logs I noticed that due to I/O errors, the background tasks will fail in further operations. Something that we should be aware of.

Here is one example:

```
Traceback (most recent call last):
  File "/appl/soft/4.0.0b2/lib64/python3.9/site-packages/autosubmit_api-4.0.0b2-py3.9.egg/autosubmit_api/experiment/common_db_requests.py", line 263, in create_many_job_times
    conn.commit()
sqlite3.OperationalError: disk I/O error

Error on Insert : OperationalError
Traceback (most recent call last):
  File "/appl/soft/4.0.0b2/lib64/python3.9/site-packages/autosubmit_api-4.0.0b2-py3.9.egg/autosubmit_api/experiment/common_db_requests.py", line 260, in create_many_job_times
    cur.executemany(sql, list_job)
sqlite3.DatabaseError: database disk image is malformed

Error on Insert : DatabaseError
Traceback (most recent call last):
  File "/appl/soft/4.0.0b2/lib64/python3.9/site-packages/autosubmit_api-4.0.0b2-py3.9.egg/autosubmit_api/experiment/common_db_requests.py", line 260, in create_many_job_times
    cur.executemany(sql, list_job)
sqlite3.DatabaseError: database disk image is malformed

Error on Insert : DatabaseError
Traceback (most recent call last):
  File "/appl/soft/4.0.0b2/lib64/python3.9/site-packages/autosubmit_api-4.0.0b2-py3.9.egg/autosubmit_api/experiment/common_db_requests.py", line 260, in create_many_job_times
    cur.executemany(sql, list_job)
sqlite3.DatabaseError: database disk image is malformed
```

Luckily, in this last example, the table is truncated every time it is populated (which is inefficient). So, the corrupted table is fixed on the next execution.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @manuel-g-castro on Feb 15, 2024, 10:26

@LuiggiTenorioK to include db-fix to the api.

**Comment by LuiggiTenorioK** [comment]
@dbeltrankyl @kinow can you elaborate on which is the strategy used to fix the db file in Autosubmit? I wonder if I can call the same procedure from the API to avoid reimplementation

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Feb 15, 2024, 15:55

You can check the function [database_fix](https://earth.bsc.es/gitlab/es/autosubmit/-/blame/master/autosubmit/autosubmit.py?page=5#L4283)
```python
@staticmethod
    def database_fix(expid):
        """
        Database methods. Performs a sql dump of the database and restores it.

        :param expid: experiment identifier
        :type expid: str
        :return:
        :rtype:        
        """
        os.umask(0) # Overrides user permissions
        current_time = int(time.time())
        corrupted_db_path = os.path.join(BasicConfig.JOBDATA_DIR, "job_data_{0}_corrupted.db".format(expid))

        database_path = os.path.join(BasicConfig.JOBDATA_DIR, "job_data_{0}.db".format(expid))
        database_backup_path = os.path.join(BasicConfig.JOBDATA_DIR, "job_data_{0}.sql".format(expid))
        dump_file_name = 'job_data_{0}.sql'.format(expid, current_time)
        dump_file_path = os.path.join(BasicConfig.JOBDATA_DIR, dump_file_name)
        bash_command = 'cat {1} | sqlite3 {0}'.format(database_path, dump_file_path)
        try:
            if  os.path.exists(database_path):
                os.popen("mv {0} {1}".format(database_path, corrupted_db_path)).read()
                time.sleep(1)
                Log.info("Original database moved.")
            try:
                exp_history = ExperimentHistory(expid, jobdata_dir_path=BasicConfig.JOBDATA_DIR,
                                                historiclog_dir_path=BasicConfig.HISTORICAL_LOG_DIR)
                Log.info("Restoring from sql")
                os.popen(bash_command).read()
                exp_history.initialize_database()

            except:
                Log.warning("It was not possible to restore the jobs_data.db file... , a new blank db will be created")
                result = os.popen("rm {0}".format(database_path)).read()

                exp_history = ExperimentHistory(expid, jobdata_dir_path=BasicConfig.JOBDATA_DIR,
                                                historiclog_dir_path=BasicConfig.HISTORICAL_LOG_DIR)
                exp_history.initialize_database()
        except Exception as exp:
            Log.critical(str(exp))

```
