### ISSUE TITLE
"API couldn't retrieve the requested information on time" error

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#68]
In GitLab by @nunomrm on Feb 22, 2024, 17:54

Hi @LuiggiTenorioK. Maybe this is an easy error,  but I can not open the Autosubmit GUI. I even deleted and re-clonned autosubmitreact and did [all the required steps](https://earth.bsc.es/gitlab/es/autosubmitreact/-/wikis/Locally-run-v4.0.0-beta.2-GUI-for-Climate-DT-VM-users) and this error happens:

![Screenshot_from_2024-02-22_17-35-38](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/0f30ffc2f90e243a5cdc1eb537dea4df/Screenshot_from_2024-02-22_17-35-38.png)

**Note 1:**

I tried these two links, and both on Chrome and Firefox (and in Incognito mode too):

```
  Local:            http://localhost:3000/autosubmitapp
  On Your Network:  http://192.168.20.75:3000/autosubmitapp
```

**Note 2:**

My ssh command was 
```
ssh -N -L 9487:nid002507:9487 rochamon@lumi.csc.fi
```

**Note 3:**

When I did the `npm install` command on the steps I mentioned above, there were these issues:
```
sh: 1: opencollective: not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2083 packages from 987 contributors and audited 2093 packages in 21.034s

143 packages are looking for funding
  run `npm fund` for details

found 285 vulnerabilities (3 low, 113 moderate, 124 high, 45 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

And I ran `npm audit fix` and there were still 33 vulnerabilities.

FYI @mcastril @kinow

**Comment by LuiggiTenorioK** [comment]
In GitLab by @nunomrm on Feb 22, 2024, 18:03

I noticed I used the `v4.0.0-beta.2`, but that there is the `v4.0.0-beta.3` branch too. But I'm not sure if that is the issue here.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @nunomrm on Feb 22, 2024, 18:09

Shortly after the localhost message I show in the issue, this appears too:
![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/9756ce3003ac00ac18243e4751f6d153/image.png)

**Comment by LuiggiTenorioK** [comment]
Hi @nunomrm. I think that the problem is in the ssh command `ssh -N -L 9487:nid002507:9487 rochamon@lumi.csc.fi`. Currently, our API is running on the Climate DT VM in port 8081, there is no API in port 9487 as far as I know.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @nunomrm on Feb 23, 2024, 09:58

I did it and the error does not happen, thanks! However, it's loading for a long time in the main page and I can't visualize anything in the GUI.
![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/b7f0254e6ecf45a63f790b91809f12f8/image.png)

**Comment by LuiggiTenorioK** [comment]
The VM seems to be overloaded sometimes. I tried to ping the API right now and it works fine, but a few minutes ago it was really slow. For now, try again to load the homepage or go directly to the URL of your experiment: https://earth.bsc.es/autosubmitapp/experiment/<your_expid>

PD: A new version of the API that is more efficient will be deployed soon

**Comment by LuiggiTenorioK** [comment]
In GitLab by @nunomrm on Feb 23, 2024, 11:33

Ok, just retried with all the steps but with `ssh -N -L 8081:nid002507:8081 rochamon@lumi.csc.fi`, as I tried before this morning. Somehow the same error I reported here initially happens now...

**Comment by LuiggiTenorioK** [comment]
Try to follow the ssh tunnel command in the guide:

```bash
ssh <your_target_ssh_host> -N -L 8081:localhost:8081
```

Just replace the `<your_target_ssh_host>` with the host name you use to access the VM.

To test if this is working correctly, do:

```bash
curl localhost:8081
# You should get: {"name":"Autosubmit API","version":"4.0.0b4"}
```

**Comment by LuiggiTenorioK** [comment]
If you do `curl localhost:8081`, it returns `{"name":"Autosubmit API","version":"4.0.0b4"}`?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @nunomrm on Feb 23, 2024, 15:07

Oh ok, it works! Thanks a lot. **I was using the LUMI login name and not the VM name**. It worked before few weeks ago when I used to login with LUMI username only.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Feb 26, 2024, 10:38

@LuiggiTenorioK I had the same issue last week at different times. By reloading the GUI several times and deactivating the Active Jobs it was finally working.

However, now it doesn't seem to work by any means

```
ssh vml -N -L 8081:localhost:8081
channel 2: open failed: connect failed: Connection refused
channel 2: open failed: connect failed: Connection refused
```

It looks like it's refusing connections. Can you observe the same?

```
curl localhost:8081
curl: (56) Recv failure: Connection reset by peer
```

**Comment by LuiggiTenorioK** [comment]
Hi Miguel, Nuno issue wasn't related to this, he just needed to fix his ssh command.

According to the logs, the server parent process was terminated this Saturday, so the server wasn't available until I rebooted it manually today.

Do you know if the VM was rebooted this weekend or something similar? Maybe we need to set up a crontab to reboot it in this case.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Feb 26, 2024, 11:07

> Hi Miguel, Nuno issue wasn't related to this, he just needed to fix his ssh command.

I know that he had a problem with the command, but I was getting exactly the same error and preferred to not open a new one.

> According to the logs, the server parent process was terminated this Saturday, so the server wasn't available until I rebooted it manually today.

When I wrote my comment I had seen this:

```
ltenorio 3895174  0.0  0.1 889884 28652 ?        Sl   Feb23   0:18 /appl/soft/4.0.0b4/bin/python /appl/soft/4.0.0b4/bin/autosubmit_api start --log-file /home/ltenorio/202402231259_api.log -w 4 -b localhost:8081 --daemon
```

Isn't it the API? 

> Do you know if the VM was rebooted this weekend or something similar? Maybe we need to set up a crontab to reboot it in this case.

```
uptime
 12:06:48 up 54 days,  3:35, 10 users,  load average: 1.14, 1.33, 1.29
```

It looks like it wasn't

**Comment by LuiggiTenorioK** [comment]
> I know that he had a problem with the command, but I was getting exactly the same error and preferred to not open a new one.

Maybe it was when the API wasn't available because I was updating it. But it was only about 5 minutes.

> When I wrote my comment I had seen this:
> 
> ```
> ltenorio 3895174  0.0  0.1 889884 28652 ?        Sl   Feb23   0:18 /appl/soft/4.0.0b4/bin/python > /appl/soft/4.0.0b4/bin/autosubmit_api start --log-file /home/ltenorio/202402231259_api.log -w 4 -b localhost:8081 --daemon
> ```
> 
> Isn't it the API? 

Yes, I saw that the parent process was alive but without any child process. At the end of the logs, I saw the children being terminated:

```
[2024-02-24 13:14:01 +0200] [3895180] [INFO] Parent changed, shutting down: <Worker 3895180>
[2024-02-24 13:14:01 +0200] [3895180] [INFO] Worker exiting (pid: 3895180)
[2024-02-24 13:14:01 +0200] [3895183] [INFO] Parent changed, shutting down: <Worker 3895183>
[2024-02-24 13:14:01 +0200] [3895183] [INFO] Worker exiting (pid: 3895183)
```

Usually, this happens when the parent is about to be terminated. But for some reason, it was still alive.

But looking at the logs immediately before this happened I saw this:

```
Must update a0s8
Traceback (most recent call last):
  File "/appl/soft/4.0.0b4/lib64/python3.9/site-packages/autosubmit_api-4.0.0b4-py3.9.egg/autosubmit_api/database/db_jobdata.py", line 622, in calculate_drawing
    result = graph.create('dot', format="plain")
  File "/appl/soft/4.0.0b4/lib/python3.9/site-packages/pydotplus-2.0.2-py3.9.egg/pydotplus/graphviz.py", line 1994, in create
    p = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1770, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory

Exception while calculating coordinates [Errno 12] Cannot allocate memory
Time Spent in a0s8: 0 seconds.
[2024-02-24 13:12:10 +0200] [3895165] [WARNING] Missing PROCESSORS_PER_NODE. Should be set if TASKS or NODES are defined. The SIM PROCESSORS will used instead.
[2024-02-24 13:12:11 +0200] [3895165] [WARNING] Missing PROCESSORS_PER_NODE. Should be set if TASKS or NODES are defined. The SIM PROCESSORS will used instead.
Wrapper table not found, trying packages.
Must update a0s9
```

Remember that a0s9 is a massive experiment (>100k jobs). One possible cause is that the VM doesn't have enough resources to calculate that big graph.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Feb 26, 2024, 18:30

> Maybe it was when the API wasn't available because I was updating it. But it was only about 5 minutes.

I think it happened at least in two different moments, but it could also be that the API was very busy.

> Yes, I saw that the parent process was alive but without any child process. At the end of the logs, I saw the children being terminated:

That was what I was about to say, that it only had a parent process.

> Remember that a0s9 is a massive experiment (>100k jobs). One possible cause is that the VM doesn't have enough resources to calculate that big graph.

The machine is using Virtual Memory now, it's at 33% of the main memory but it's obviously short for some operations. We could ask for an upgrade to CSC
