### ISSUE TITLE
GUI: Wrappers order in the Tree View

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#8]
In GitLab by @mcastril on Apr 4, 2022, 11:28

@wuruchi do you think that wrappers could be ordered in alphabetical order? I think this will lead to a temporal order which would make easier to follow.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 4, 2022, 11:28

moved from autosubmit#803

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 4, 2022, 11:52

Hello @mcastril 

Sure. I am currently working on some tests for the Tree View. I'll add this feature and its test cases.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Apr 4, 2022, 11:59

Hi @wuruchi. Sorry that I didn't see this at first. But given that this is not super-high priority I think this is something that @ jberlin could see how to improve and provide a solution here, and apply the changes with your supervision.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @wuruchi on Apr 4, 2022, 12:27

Sure, although @ jberlin would've to look into the `API`  since the ordering is generated there.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 12:13

Hi @mcastril , Can you please provide an existing example of wrong ordering in experiments with wrappers ? this issue applies both vertical and horizontal wrappers ? I checked one and I think it looks good or I am missing something:

https://earth.bsc.es/autosubmitapp/experiment/a11x

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jul 5, 2022, 14:48

This example (with only 2 wrappers you have many chances of having a good ordering even if it's totally random):

https://earth.bsc.es/autosubmitapp/experiment/a28v

It affects at least vertical wrappers, and if there's no forced ordering I think that it necessarily will affect any wrapper.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 14:59

thanks for the example @mcastril

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 5, 2022, 17:23

I created a new branch (AS_API_Issue_803_ordering_wrappers) to test the changes done, I will debug in the development machine

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 6, 2022, 15:05

I think we should ask support to add our dev env url to CAS registry, I am trying to test the changes done in  the ordering of wrappers in the tree view

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/df31302f9e76f5f824f315ed7ea43ed7/image.png)

I will send them an email to do this

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jul 6, 2022, 16:35

I thought that we had disabled the CAS authentication in the dev. webserver. It's not open to outside so it wouldn't be any security risk.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 6, 2022, 16:38

yes, that is true, but I think some features requires the user to be authenticated based on some Wilmer comments

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jul 6, 2022, 16:41

By the moment you could fake your authentication if that's possible. In the end, you will not be able to log in as any other user through CAS.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 6, 2022, 16:42

ok sounds good

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 10:45

yesteday after updating the API in the VM, I ran on this error:

```
[2022-07-07 09:52:47 +0000] [436880] [INFO] RUN|RECEIVED|
[2022-07-07 09:52:47 +0000] [436880] [ERROR] Exception on /running/ [GET]
Traceback (most recent call last):
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/autosubmit_api/app.py", line 215, in search_running
    result = get_current_running_exp()
  File "/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/autosubmit_api/database/db_common.py", line 421, in get_current_running_exp
    cursor.execute(query)
OperationalError: no such table: listexp
```


is it weird since I did not modify anything related to it since. I will try to figure out what can be

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 17:24

I found and solved the issue, the container AS installation overwrote the AS configs by default ones, I restore these and now it works :O)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 17:26

I guess is enough to copy the experiment you mentioned @mcastril that has wrappers to the VM so I can test the changes and see how it works with a real example. do I need to do also some other stuff of with just copying the folder is enought ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 7, 2022, 17:36

I found one so there is no need to copy anything:

`http://84.88.189.213/autosubmitapp/experiment/a4h9`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Jul 8, 2022, 09:28

I was going to ask if there wasn't any other experiment having wrappers, I thought I remembered that we had at least one.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 8, 2022, 09:36

Hi @mcastril I can search, anyways the changes I did not work as expected, I need to dig more in the code

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 12:58

I just finished the changes and it seems that it works fine, who can validate this ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:00

I'm not using the GUI regularly, so maybe @eferre1 can validate it better than me ( if he has time)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:30

I have to run some "long" experiments (5 members - 20 chunks) for auto-ecearth3#1758, so I will be able to check it soon if it is not too urgent.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 14:32

It needs to be tested in the development environment, where the changes are deployed

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:34

In that case

@ jberlin maybe you can copy the tests that @eferre1 will use and run them with project_type = None and afterwards, compare them

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 14:36

yeah sounds good, after @eferre1 finished running the exp we can compare both in dev and production

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:39

If you can open ongoing experiments in the development environment (or copy the .db files to "fake clone" them), then you could use the `a28v` experiment that is already running with wrappers and in the current GUI tree view is not being sorted out (the current running wrapper is in the middle of the wrappers list). 

If not, don't try to run a copy of it though, it is the VHR run from Edu and it cannot run in the normal queues of bsc32 accounts, we will do it once I have the other experiments finished.

PS: although in that experiment the GUI shows this in red at the top: `database disk image is malformed` (not sure if it affects something)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 14:42

In Autosubmit debug mode, ( project_type = None ) , it can run anything as it doesn't run the real templates, only the workflow structure. Would just be a matter of changing the platform.conf to the bsc user (and the QUEUE to debug to speedup the queuing time)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 14:49

Ok, I didn't know that, then yes, you could already check with that a28v experiment (it is a big one), or wait for my runs to do it.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 15:43

so cpying these files /esarchive/autosubmit/a28v to the virtual machine Autosubmit folder will be enough o check this properly ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @dbeltrankyl on Jul 14, 2022, 15:52

No, because it won't be registered in the DB and the GUI won't see the experiment ( I believe) 

What I do to test an office experiment in my local home is to: 

1. Create a new experiment with `autosubmit expdef -dm`
1. `scp office:/esarchive/autosubmit/<expid>/conf/* autosubmit/<expid>/conf`
1. Change configuration names per the name of the new expid
1. in autosubmit.conf, change `[config] EXPID = <original> EXPID = <new_id>`
1. in expdef.conf, change `[default] EXPID = <original> EXPID = <new_id>`
1. in dummy case, change project -> project_type = git for project_type = none 
1. in platform.conf, change platforms for your user.
1. in dummy case, change bsc_es or class_a per debug. 


This is because there is no way of doing an autosubmit remote copy from one machine to another ( may be worth doing this feature in the future? ) 

edit: Or a command like fixconf that does these steps

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 16:32

I simply copied it and the API picket it up:

http://84.88.189.213/autosubmitapp/experiment/a28v

@eferre1 can you please check when you have some spare time ? thanks!

**Comment by LuiggiTenorioK** [comment]
In GitLab by @eferre1 on Jul 14, 2022, 16:33

How can I check it? I cannot access that url that you mention @ jberlin

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 14, 2022, 16:45

great ! thanks @eferre1

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Jul 28, 2022, 09:37

We should plan the deployment of the new release, I guess is better to accumulate several fixes in one deploy so we dont disrupt too much the users.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Sep 28, 2022, 18:22

> the source file job_lists.py was not the latest one that is in the main branch but even replacing with the latest one the issue remains

Excuse me @ jberlin, what do you mean? Do you mean a particular `job_list` for a particular experiment?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Sep 29, 2022, 08:46

Hi @mcastril @ jberlin 

I detected where the bad sorting came from:

```
file: components/representations/tree/tree.py
line: 203

try:
  # This line of code was making the function to crash and therefore use the other load method
  # self.result_tree.sort(key=lambda x: x.title)
  
  # Fixed the above line with this:
  self.result_tree = sorted(self.result_tree, key=lambda x: x['title'])
except Exception as e:
  print("could not sort the tree by titles")
```

I spotted couple of days ago this part of the code, it was without a try catch and it was using the commented sorting function that made the **function crash** with an error and therefore **exit this method of generating the tree (willmer fast method)** and use the slower method, making some tree experiments slower than usual to load. 

I fixed it with the bellow uncommented line as I thought this was the desired sorting.

I commented out the whole block of code to test and this is how it changes

![beforenow.drawio](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/1a2ead450c6ec3834fa9966635170f83/beforenow.drawio.png)

---

Furthermore, I would like to point out an example of why a User complained about having to scroll a lot in order to access the Keys "jobs" folder:

https://earth.bsc.es/autosubmitapp/experiment/a550

or worse:

https://earth.bsc.es/autosubmitapp/experiment/a4fq

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 13:12

Hi @ggcr , these changes were done only in the source code present in the VM right ? I am not able to see them in the main branch, are these in another branch ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ggcr on Sep 29, 2022, 13:15

Yes, the changes are at the current code of the API at the VM

`/var/www/html/autosubmitapi/venv27/lib/python2.7/site-packages/autosubmit_api-1.0.24.1-py2.7.egg/autosubmit_api/components/representations/tree/tree.py`

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 15:20

mentioned in commit d42c6d59df26d61ca0b6bae7443c91a123fd3c06

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 15:24

Fixed the issue when the treview is not fully regenerated (that was the missed case) now it looks fine in all cases and the hierarchy is correct.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 15:44

sorry @mcastril , I was refering a source code file of the API, not the jobs of an experiment

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 17:09

I added the folder for the wrappers, initially will be displayed collapsed

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/f739d9f1b242b66375e9f1b2d82eb88e/image.png)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 17:11

mentioned in commit 04061d8716b2b6446f241242175372d201a23d41

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 17:48

I would suggest to display all startdates expanded if these are less than a certain number, for instance 5 start dates. if there are more than that all should be displaued collapsed for readability.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Sep 29, 2022, 17:49

Good job @ggcr , this was not easy to spot because of the silent error, and actually the benefit is twofold as you explain (performance and look).

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Sep 29, 2022, 17:50

mentioned in commit 4fb2b22851c010d26b4f9f394634c010bcfe3cf2

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Sep 29, 2022, 17:50

Perfect @ jberlin !! , please make sure that all changes arrive in the `master` as soon as they are tested.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Sep 29, 2022, 17:51

This makes sense, we have to make rational use of the space.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 6, 2022, 13:16

as discussed in the MWT concerning the member folders in the top of the treeview, I will move the label to the parent in case all jobs are completed, and expand those that have at least one failed job

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 6, 2022, 16:28

mentioned in commit b56a3169a25679206cff409db319a68d14904f38

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Oct 6, 2022, 17:01

Sorry @ jberlin. Apparently, we only discussed this feature in the meeting. It should be:

* If startdates > threshold: 
  * For each startdate
    * If all jobs in [WAITING, SUSPENDED]
      * Collapse and add the label

We can skip READY as it's ephemeral. All of RUNNING, FAILED, QUEUING, SUBMITTED are considered ACTIVE

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 6, 2022, 17:28

so if for a given member, there is any job with status RUNNING, FAILED, QUEUING or SUBMITTED we should display the member in the tree expanded right ?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Oct 7, 2022, 17:13

Yes. Basically all the members, because once you uncollapse one startdate all the members appear.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 7, 2022, 18:17

mentioned in commit 90ee6a3770dab4cc13c5b713757f1495f6cc997e

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 17, 2022, 18:00

mentioned in commit 4003018ad9337dc98c1af1a03755c2504d125c3c

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 20, 2022, 15:41

mentioned in commit 9147f87fb1541e7ca5ec1f9224b647fb87646d07

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 21, 2022, 16:53

mentioned in commit 431e458f2c6d18b06bdbef55c5124ab979c6d420

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 21, 2022, 16:54

I applied the last set of changes, so I think now this is completed.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Oct 21, 2022, 16:57

you can check how it looks the a550 now in DEV:

https://bscesautosubmitdev01.bsc.es/autosubmitapp/experiment/a550

and in production:

https://earth.bsc.es/autosubmitapp/experiment/a550

the sorting is correct and these show the startdates that are completed all collpased and wrappers are now in a folder

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Nov 14, 2022, 16:33

Validated in development VM

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Dec 1, 2022, 14:10

I've seen that in these cases folders appear collapsed by default, even if they contain active jobs. Folder with active jobs should be expanded by default:

![Screenshot_from_2022-12-01_14-04-27](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/0ac9473bf5015a071fc3ff29087736a3/Screenshot_from_2022-12-01_14-04-27.png)
![Screenshot_from_2022-12-01_14-04-18](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/c0c189ae31322de28544dabf5092e878/Screenshot_from_2022-12-01_14-04-18.png)

Note that also in the first one the collapse / expand buttons are missing, maybe because it only has one folder?

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Dec 1, 2022, 14:21

Hi @mcastril , the original idea was to apply this to the top level (start dates) to improve readability and move the tooltip to the upper level if the jobs of the folder are all inactives, the second level was not contemplate in the solution

**Comment by LuiggiTenorioK** [comment]
In GitLab by @ jberlin on Dec 1, 2022, 14:25

original example after the changes:

![image](https://earth.bsc.es/gitlab/es/autosubmit-api/uploads/01f782067529ddf4ccf0f08bf0b37759/image.png)

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Dec 1, 2022, 14:42

mentioned in issue autosubmitreact#44

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Dec 1, 2022, 14:46

Yes, that's the point: if all the tasks are inactive. As you can see, there's one running task in one of the folders. Sorry, don't understand what you meant about the second level.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @mcastril on Dec 1, 2022, 14:52

Got it, the change was only applied to the startdate level, and the collapse on the member level was not taking into account the status of the inner tasks already.
