### ISSUE TITLE
HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-api#95]
In GitLab by @agarci3 on Nov 4, 2024, 10:25

Hi @LuiggiTenorioK 

I am getting this error when running the testing suite:

```
Traceback (most recent call last):
  File "/esarchive/exp/monarch/testing_suite/source/./testing_suite.py", line 895, in <module>
    suite.main()
  File "/esarchive/exp/monarch/testing_suite/source/./testing_suite.py", line 660, in main
    my_experiments = self.create_experiments()
  File "/esarchive/exp/monarch/testing_suite/source/./testing_suite.py", line 632, in create_experiments
    my_experiment = Experiment_Factory.create(
  File "/esarchive/exp/monarch/testing_suite/source/experiment/experiment_factory.py", line 13, in create
    return Monarch_Experiment(expid, my_config, cmd_interface, benchmark, api_interface)
  File "/esarchive/exp/monarch/testing_suite/source/experiment/monarch_experiment.py", line 11, in __init__
    super(Monarch_Experiment, self).__init__(expid, my_config, cmd_interface, benchmark, api_interface)
  File "/esarchive/exp/monarch/testing_suite/source/experiment/experiment.py", line 64, in __init__
    "DESCRIPTION": self.description.partition(': ')[2] or self.description,
  File "/esarchive/exp/monarch/testing_suite/source/experiment/experiment.py", line 185, in description
    response = self.api_interface.experiment_info(self.id)
  File "/esarchive/exp/monarch/testing_suite/source/api_interface/autosubmit_interface.py", line 37, in experiment_info
    return self.__request(concatenated_request)
  File "/esarchive/exp/monarch/testing_suite/source/api_interface/autosubmit_interface.py", line 28, in __request
    raise RuntimeError("API response error on " + request_url + ": " + response.raise_for_status())
  File "/shared/earth/easybuild/rocky/8.4/x86_64/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://earth.bsc.es/autosubmitapi/expinfo/t0fr
```

Any idea what could be happening?

Let me know if you think this is not coming from the API.

FYI: @gmontanepinto

**Comment by LuiggiTenorioK** [comment]
Hi @agarci3,

Since the latest version of the API, routes have been removed from the root path to favor versioned routes. You'll have to add `/v3` to the route to make it work as it was e.g. instead of using `https://earth.bsc.es/autosubmitapi/expinfo/t0fr` use `https://earth.bsc.es/autosubmitapi/v3/expinfo/t0fr`.

**Comment by LuiggiTenorioK** [comment]
In GitLab by @agarci3 on Nov 4, 2024, 10:52

Great, I did not know about that. 

Thanks
